name: Release from main
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver version to cut a release for (ie. 4.0.3)'
        required: true

jobs:
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: |
          GOOS=linux go build -ldflags "-X main.version=$VERSION" -o bin/log-cache-cf-plugin-linux
          GOOS=darwin go build -ldflags "-X main.version=$VERSION" -o bin/log-cache-cf-plugin-darwin
          GOOS=windows go build -ldflags "-X main.version=$VERSION" -o bin/log-cache-cf-plugin-windows
        env:
          VERSION: ${{ github.event.inputs.version }}
      - run: |
          gh release create -d -t "v$VERSION" --generate-notes "v$VERSION" ./bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
